# Generated by Django 2.0.5 on 2018-05-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0002_state_code'),
        ('city', '0001_initial'),
        ('location', '0001_initial'),
        ('suburb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ine', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=20)),
                ('street_between', models.CharField(max_length=100)),
                ('street_and_between', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.City')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.State')),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suburb.Suburb')),
            ],
        ),
    ]
