# Generated by Django 2.0.5 on 2018-05-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='agent_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(choices=[('Promotor', 'Promotor'), ('Invitado', 'Invitado')], max_length=50, null=True),
        ),
    ]
